In [1]:
import numpy as np

In [3]:
NONE = 0
WHITE = 1
BLUE = 2
GREEN = 3
RED = 4
ORANGE = 5
YELLOW = 6

In [4]:
cube = np.zeros(shape=(3,3,3,3), dtype=np.uint8)
cube[:, :, 0, 2] = WHITE  # Front Face
cube[:, :, 2, 2] = YELLOW # Back Face
cube[:, 2, :, 1] = BLUE   # Top Face
cube[:, 0, :, 1] = RED    # Bottom Face
cube[2, :, :, 0] = GREEN  # Right Face
cube[0, :, :, 0] = ORANGE # Left Face

In [5]:
cube[:, :, 0, [0,1]]

array([[[5, 4],
        [5, 0],
        [5, 2]],

       [[0, 4],
        [0, 0],
        [0, 2]],

       [[3, 4],
        [3, 0],
        [3, 2]]], dtype=uint8)

In [4]:
base_cude = cube.copy()

Front Side Rotations

In [5]:
def F(cube):
    cube[:, :, 0] = np.rot90(cube[:, :, 0], k=3)
    cube[:, :, 0, 0], cube[:, :, 0, 1] = cube[:, :, 0, 1].copy(), cube[:, :, 0, 0].copy()
    
def F2(cube):
    cube[:, :, 0] = np.rot90(cube[:, :, 0], k=2)
    
def F_(cube):
    cube[:, :, 0] = np.rot90(cube[:, :, 0], k=1)
    cube[:, :, 0, 0], cube[:, :, 0, 1] = cube[:, :, 0, 1].copy(), cube[:, :, 0, 0].copy()

Back Side Rotation

In [6]:
def B(cube):
    cube[:, :, 2] = np.rot90(cube[:, :, 2], k=1)
    cube[:, :, 2, 0], cube[:, :, 2, 1] = cube[:, :, 2, 1].copy(), cube[:, :, 2, 0].copy()
    
def B2(cube):
    cube[:, :, 2] = np.rot90(cube[:, :, 2], k=2)
    
def B_(cube):
    cube[:, :, 2] = np.rot90(cube[:, :, 2], k=3)
    cube[:, :, 2, 0], cube[:, :, 2, 1] = cube[:, :, 2, 1].copy(), cube[:, :, 2, 0].copy()

Right Face Rotation

In [7]:
def R(cube):
    cube[2, :, :] = np.rot90(cube[2, :, :], k=1)
    cube[2, :, :, 1], cube[2, :, :, 2] = cube[2, :, :, 2].copy(), cube[2, :, :, 1].copy()

def R2(cube):
    cube[2, :, :] = np.rot90(cube[2, :, :], k=2)
    
def R_(cube):
    cube[2, :, :] = np.rot90(cube[2, :, :], k=3)
    cube[2, :, :, 1], cube[2, :, :, 2] = cube[2, :, :, 2].copy(), cube[2, :, :, 1].copy()

Left Face Rotation

In [8]:
def L(cube):
    cube[0, :, :] = np.rot90(cube[0, :, :], k=3)
    cube[0, :, :, 1], cube[0, :, :, 2] = cube[0, :, :, 2].copy(), cube[0, :, :, 1].copy()
    
def L2(cube):
    cube[0, :, :] = np.rot90(cube[0, :, :], k=2)
    
def L_(cube):
    cube[0, :, :] = np.rot90(cube[0, :, :], k=1)
    cube[0, :, :, 1], cube[0, :, :, 2] = cube[0, :, :, 2].copy(), cube[0, :, :, 1].copy()

Top Face Rotation

In [9]:
def T(cube):
    cube[:, 2, :] = np.rot90(cube[:, 2, :], k=3)
    cube[:, 2, :, 0], cube[:, 2, :, 2] = cube[:, 2, :, 2].copy(), cube[:, 2, :, 0].copy()
    
def T2(cube):
    cube[:, 2, :] = np.rot90(cube[:, 2, :], k=2)
    
def T(cube):
    cube[:, 2, :] = np.rot90(cube[:, 2, :], k=1)
    cube[:, 2, :, 0], cube[:, 2, :, 2] = cube[:, 2, :, 2].copy(), cube[:, 2, :, 0].copy()

Down Face Rotation

In [10]:
def D(cube):
    cube[:, 0, :] = np.rot90(cube[:, 0, :], k=1)
    cube[:, 0, :, 0], cube[:, 0, :, 2] = cube[:, 0, :, 2].copy(), cube[:, 0, :, 0].copy()
    
def D2(cube):
    cube[:, 0, :] = np.rot90(cube[:, 0, :], k=2)
    
def D_(cube):
    cube[:, 0, :] = np.rot90(cube[:, 0, :], k=3)
    cube[:, 0, :, 0], cube[:, 0, :, 2] = cube[:, 0, :, 2].copy(), cube[:, 0, :, 0].copy()

In [52]:
R(cube)
D(cube)
(cube == base_cude).all()

False

In [11]:
R(cube)
D(cube)

In [53]:
cube[0, 2, 0]

array([5, 2, 1], dtype=uint8)

In [54]:
base_cude[0, 2, 0]

array([5, 2, 1], dtype=uint8)

In [55]:
cube

array([[[[4, 3, 1],
         [3, 1, 0],
         [5, 1, 4]],

        [[5, 0, 1],
         [5, 0, 0],
         [5, 0, 6]],

        [[5, 2, 1],
         [5, 2, 0],
         [5, 2, 6]]],


       [[[0, 2, 3],
         [0, 4, 0],
         [0, 4, 3]],

        [[0, 0, 1],
         [0, 0, 0],
         [0, 0, 6]],

        [[0, 2, 1],
         [0, 2, 0],
         [0, 2, 6]]],


       [[[2, 3, 1],
         [3, 6, 0],
         [3, 4, 6]],

        [[6, 0, 4],
         [3, 0, 0],
         [1, 0, 4]],

        [[6, 2, 3],
         [5, 4, 0],
         [4, 6, 5]]]], dtype=uint8)